(() => {
  // utils/i18n.ts
  var translations = {
    en: {
      header: {
        title: "Neural Pad",
        lastSaved: "Last saved:",
        toggleNotes: "Toggle Notes Sidebar",
        save: "Save Note (Ctrl+S)",
        saveAs: "Save As...",
        settings: "Settings",
        help: "Help",
        lock: "Lock Note",
        unlock: "Remove Lock",
        download: "Download",
        backToLanding: "Back to Landing Page"
      },
      defaultNoteTitle: "Untitled Note",
      editor: {
        placeholder: "Start writing your next great idea..."
      },
      notesSidebar: {
        title: "My Notes",
        newNote: "New Note",
        searchPlaceholder: "Search notes...",
        deleteNote: "Delete note",
        tagsTitle: "Tags",
        allNotes: "All Notes",
        sortRecent: "\u{1F4C5} Most Recent",
        sortOldest: "\u{1F550} Oldest First",
        sortAlphabetical: "\u{1F524} A-Z",
        pinned: "Pinned",
        today: "Today",
        yesterday: "Yesterday",
        thisWeek: "This Week",
        thisMonth: "This Month",
        older: "Older"
      },
      chat: {
        title: "AI Chat Assistant",
        open: "Open Chat",
        close: "Close Chat",
        placeholder: "Ask anything...",
        send: "Send",
        thinking: "Thinking...",
        startConversation: "Ask me a question to get started!",
        sessionError: "Chat session not initialized. Please try again.",
        toggleWebSearch: "Toggle Web Search",
        sources: "Sources",
        insertToEditor: "Insert to Editor",
        insertedToEditor: "Inserted to editor"
      },
      contextMenu: {
        improve: "Improve writing",
        fix: "Fix spelling & grammar",
        summarize: "Summarize",
        generateTags: "Generate Tags",
        describeImage: "Describe image",
        suggestCaption: "Suggest a caption",
        makeTable: "Convert to Table",
        shareSelection: "Share selection",
        shareImage: "Share image",
        setReminder: "Set Reminder",
        defaultSelectionTitle: "Neural Pad Selection",
        table: {
          title: "Table",
          sortAZ: "Sort A\u2192Z (column)",
          sortZA: "Sort Z\u2192A (column)",
          totals: "Add totals row",
          zebra: "Toggle zebra",
          sticky: "Toggle sticky header",
          borders: "Borders",
          bordersAll: "All",
          bordersOutside: "Outside",
          bordersNone: "None",
          copyCsv: "Copy as CSV"
        },
        customPromptPlaceholder: "Or type your own prompt...",
        submit: "Submit"
      },
      settings: {
        title: "Settings",
        theme: "Appearance",
        themes: {
          default: "Default",
          twilight: "Twilight",
          ocean: "Ocean",
          forest: "Forest",
          blossom: "Blossom",
          dusk: "Dusk"
        },
        language: "Language",
        autoSave: "Auto-Save",
        autoSaveDescription: "Automatically save the current note every 5 minutes.",
        apiProvider: "AI Provider",
        modelConfig: "Gemini Model Configuration",
        model: "Model",
        temperature: "Temperature",
        topK: "Top-K",
        topP: "Top-P",
        apiKey: "API Key",
        apiKeyPlaceholder: "Enter your API key here",
        getApiKeyHere: "Get your {{provider}} API key here",
        deleteApiKey: "Delete API Key",
        confirmDeleteApiKey: "Are you sure you want to delete this API key? This action cannot be undone.",
        apiKeyDeleted: "API key deleted successfully",
        showApiKey: "Show API Key",
        hideApiKey: "Hide API Key",
        export: {
          title: "Export & Backup",
          backupTitle: "Full Backup",
          backupDescription: "Download all notes and settings as JSON. Perfect for backup before formatting your device.",
          downloadBackup: "Download Complete Backup",
          restoreBackup: "Restore from Backup",
          importSuccess: "Successfully imported {{count}} notes!",
          importError: "Failed to import backup",
          exportTitle: "Export as Documents",
          exportDescription: "Export all notes as HTML or Markdown files in a ZIP archive."
        }
      },
      notifications: {
        noteSaved: "Note saved successfully!",
        saveError: "Failed to save note: {{message}}",
        noteDeleted: "Note deleted.",
        deleteError: "Failed to delete note: {{message}}",
        loadError: "Failed to load notes: {{message}}",
        aiThinking: "AI is thinking...",
        aiSuccess: "AI task completed!",
        aiError: "AI Error: {{message}}",
        quotaError: "You have exceeded your quota for {{provider}}. Please check your plan and billing details on their website.",
        apiKeyInvalid: "Your {{provider}} API key appears to be invalid or missing. Please check it in Settings.",
        apiKeyMissingAction: "API key is missing. Click here to open Settings and add it.",
        noTagsFound: "No relevant tags were found.",
        noteLocked: "Note locked.",
        wrongPassword: "Wrong password.",
        lockRemoved: "Lock removed.",
        cannotSaveLocked: "Cannot save locked note without password.",
        shareSuccess: "Shared successfully.",
        shareUnavailable: "Sharing not available here. Copied to clipboard instead.",
        exportedAsJson: "Note exported as JSON successfully!",
        exportSuccess: "Exported as {{format}} successfully!",
        exportError: "Export failed: {{message}}"
      },
      common: {
        save: "Save",
        cancel: "Cancel",
        delete: "Delete",
        close: "Close",
        apply: "Apply",
        preview: "Preview",
        markdown: "Markdown",
        loading: "Loading...",
        restore: "Restore"
      },
      saveAs: {
        title: "Save As",
        filename: "File Name",
        format: "Save as Type",
        selectFormat: "Select a format to export your note",
        export: "Export"
      },
      history: {
        title: "History",
        empty: "No history records yet",
        selectVersion: "Select a version"
      },
      welcome: {
        title: "Welcome to Neural Pad",
        subtitle: "Your intelligent writing companion, powered by Google's Gemini. Enhance your creativity, streamline your workflow, and bring your ideas to life.",
        feature1Title: "AI-Powered Writing",
        feature1Description: "Improve, summarize, or fix grammar in your selected text with a single click.",
        feature2Title: "Visual Intelligence",
        feature2Description: "Right-click on images to generate descriptions or creative captions.",
        feature3Title: "Conversational AI",
        feature3Description: "Chat with the AI to brainstorm ideas, ask questions, or get research help.",
        feature4Title: "Smart Organization",
        feature4Description: "Automatically generate relevant tags for your notes to keep everything organized.",
        cta: "Get Started",
        quickLinks: {
          features: "Features",
          items: {
            aiChat: "AI Chat",
            imageAnalysis: "Image Analysis",
            tagging: "Tagging"
          },
          support: "Support",
          privacyPolicy: "Privacy Policy",
          termsOfService: "Terms of Service",
          contact: "Contact"
        }
      },
      landingPage: {
        heroTitle: "Rethink Your Notes.",
        heroSubtitle: "AI-powered smart notebook. Write, organize, secure your notes and enhance them with artificial intelligence.",
        cta: "Launch Writer",
        featuresTitle: "Designed for Clarity and Power",
        mockupsTitle: "Product Screenshots",
        mockupsSubtitle: "Highlighted screens from the app",
        mockupsItems: {
          i1: { title: "Improve Writing", desc: "Make selected text clearer, concise, and more engaging with AI." },
          i2: { title: "Fix Spelling & Grammar", desc: "Correct mistakes automatically while preserving your tone." },
          i3: { title: "Summarize", desc: "Condense long passages into a few key points with one click." },
          i4: { title: "Generate Tags", desc: "Auto-generate relevant tags for faster organization." },
          i5: { title: "Make Blueprint", desc: "Generate a Make.com blueprint directly from your selection." },
          i6: { title: "Suggest Caption", desc: "Get creative, catchy captions for your images." },
          i7: { title: "Describe Image", desc: "Ask AI to describe images in detail for accessibility and clarity." },
          i8: { title: "Chat Assistant", desc: "Context-aware chat to brainstorm ideas and research." }
        },
        newFeaturesTitle: "What's New",
        newFeatures: {
          backupTitle: "Export & Backup",
          backupDesc: "Download all notes as HTML/Markdown or full JSON backups.",
          secureTitle: "Encrypted Notes",
          secureDesc: "Lock notes with a password. Content stays encrypted."
        },
        downloadTitle: "Get the Desktop App",
        downloadSubtitle: "Enjoy a focused, native experience on your favorite operating system. (Coming Soon)",
        downloadFor: "Download for",
        footerText: "\xA9 {{year}} Neural Pad. All rights reserved.",
        contactEmail: "Contact us at"
      },
      help: {
        title: "Help & Shortcuts",
        quickStart: "Quick Start",
        quickStartStep1: "Create a new note from the sidebar and give it a title.",
        quickStartStep2: "Start writing. Select text and right-click for AI actions.",
        quickStartStep3: "Open the Chat to brainstorm or research with AI.",
        quickStartStep4: "Use Settings to choose AI provider, theme, and export notes.",
        writingAssistant: "AI Writing Assistant",
        writingAssistantDesc: "Select any text in the editor and right-click to open the AI context menu. You can improve writing, fix grammar, summarize, and more.",
        imageTools: "AI Image Tools",
        imageToolsDesc: "Right-click on any image you've pasted into the editor to generate descriptions or captions. On mobile, tap the wand icon on the image.",
        chat: "AI Chat",
        chatDesc: "Open the chat sidebar to have a conversation with the AI. It can help with brainstorming, research, or answering questions. Toggle web search for up-to-date information.",
        organization: "Organization & Tags",
        organizationDesc: "Use the 'Generate Tags' AI action to automatically tag your notes. Filter your notes by tag in the sidebar.",
        voiceInput: "Voice Input",
        voiceInputDesc: "Use your voice to write notes hands-free.",
        voiceInputStep1: "Click the microphone icon in the toolbar",
        voiceInputStep2: "Speak clearly and slowly",
        voiceInputStep3: "Review the transcribed text in the modal",
        voiceInputStep4: "Click 'Add' to insert into note, or 'Cancel' to discard",
        exportBackup: "Export & Backup",
        backupTitle: "How to Backup",
        backupStep1: "Open Settings (gear icon in top bar)",
        backupStep2: "Go to 'Export & Backup' section",
        backupStep3: "Click '\u{1F4E6} Download Complete Backup' - saves as JSON file",
        restoreTitle: "How to Restore",
        restoreStep1: "After formatting, open the app",
        restoreStep2: "Open Settings \u2192 Export & Backup",
        restoreStep3: "Click '\u{1F4E5} Restore from Backup'",
        restoreStep4: "Select your JSON backup file - all data will be restored!",
        backupTip: "Tip:",
        backupTipDesc: "Keep your backup file in cloud storage (Google Drive, Dropbox) for extra safety.",
        exportBackupDesc: "Go to Settings \u2192 Export to download all notes as HTML or Markdown (ZIP).",
        storageSecurity: "Storage & Security",
        storageSecurityDesc: "Your notes are stored locally in your browser (IndexedDB). Locked notes are encrypted with your password\u2014without it, content cannot be recovered.",
        shortcuts: "Keyboard Shortcuts",
        saveNote: "Save current note",
        bold: "Toggle bold",
        italic: "Toggle italic",
        underline: "Toggle underline",
        undo: "Undo",
        redo: "Redo",
        troubleshooting: "Troubleshooting",
        troubleshootingWindow: "Electron window doesn't show: wait a few seconds after dev server starts; if needed, press Ctrl+Shift+I to open DevTools and check errors.",
        troubleshootingApi: "Missing API key warning: open Settings and add your provider key.",
        troubleshootingImages: "Cannot paste images: ensure you're pasting an image from clipboard; drag & drop or use the toolbar to upload."
      },
      aiPrompts: {
        languageInstruction: "Please provide the response in the same language as the selected text.",
        responseTitle: "AI Response",
        improveWriting: "Improve the writing of the following text, making it more clear, concise, and engaging",
        fixSpelling: "Fix any spelling and grammar mistakes in the following text",
        summarize: "Summarize the following text into a few key points",
        generateTags: "Generate relevant tags for the following text",
        describeImage: "Describe this image in detail",
        suggestCaption: "Suggest a creative and engaging caption for this image",
        makeTable: "Convert the selected text into a clear table. Output CSV only without commentary."
      },
      openNote: {
        noNotes: "No notes yet. Create one!"
      },
      password: {
        setTitle: "Set Password",
        unlockTitle: "Enter Password",
        removeTitle: "Remove Lock",
        passwordLabel: "Password",
        placeholder: "Enter password",
        confirm: "Confirm"
      },
      voice: {
        start: "Start Voice Input",
        stop: "Stop Voice Input",
        error: "Voice recognition error",
        networkError: "Network error. Please check your internet connection.",
        permissionError: "Microphone permission denied. Please check browser settings.",
        serviceNotAllowedError: "Voice recognition service not allowed. Please check browser settings.",
        badGrammarError: "Voice recognition grammar error. Please try again.",
        languageNotSupportedError: "Unsupported language. Please select a different language.",
        listening: "Listening...",
        processing: "Processing...",
        readyToRecord: "Ready to record",
        insert: "Insert"
      },
      toolbar: {
        bold: "Bold",
        italic: "Italic",
        underline: "Underline",
        strike: "Strikethrough",
        code: "Code",
        bulletList: "Bullet List",
        orderedList: "Numbered List",
        blockquote: "Blockquote",
        insertImage: "Insert Image",
        attachFile: "Attach File",
        insertTable: "Insert Table",
        undo: "Undo",
        redo: "Redo"
      },
      share: {
        title: "Share Note",
        email: "Email",
        copy: "Copy",
        download: "Download",
        format: "Select Format",
        htmlNote: "Includes images, opens in browser",
        pdfNote: "Print dialog will open",
        jsonNote: "For backup/programming",
        txtNote: "Plain text only",
        pdfPrintOpened: "PDF print dialog opened",
        systemShare: "System Share",
        systemShareDesc: "Share as file via OS dialog",
        or: "OR",
        fullNote: "Full Note",
        selection: "Selection",
        shareAsText: "Share as Text",
        otherActions: "Other Actions"
      },
      reminder: {
        title: "\u{1F514} Set Reminder",
        quickOptions: "Quick Options",
        in1Hour: "In 1 hour",
        in3Hours: "In 3 hours",
        tomorrow: "Tomorrow morning",
        nextWeek: "In 1 week",
        customDate: "Custom Date/Time",
        addToCalendar: "Add to Calendar",
        save: "Save",
        remove: "Remove",
        setSuccess: "Reminder set!",
        removed: "Reminder removed",
        pastDateError: "Cannot select a past date",
        selectDateFirst: "Select a date first",
        calendarOpened: "Calendar opened",
        reminderNotification: "\u23F0 Reminder: {{title}}",
        alertTitle: "\u23F0 Reminder!",
        goToNote: "Go to Note"
      }
    },
    tr: {
      header: {
        title: "Neural Pad",
        lastSaved: "Son kay\u0131t:",
        toggleNotes: "Not Kenar \xC7ubu\u011Funu A\xE7/Kapat",
        save: "Notu Kaydet (Ctrl+S)",
        saveAs: "Farkl\u0131 Kaydet...",
        settings: "Ayarlar",
        help: "Yard\u0131m",
        lock: "Notu Kilitle",
        unlock: "Kilidi Kald\u0131r",
        download: "\u0130ndir",
        backToLanding: "Ana Sayfaya D\xF6n"
      },
      defaultNoteTitle: "Ba\u015Fl\u0131ks\u0131z Not",
      editor: {
        placeholder: "Bir sonraki harika fikrinizi yazmaya ba\u015Flay\u0131n..."
      },
      notesSidebar: {
        title: "Notlar\u0131m",
        newNote: "Yeni Not",
        searchPlaceholder: "Notlarda ara...",
        deleteNote: "Notu sil",
        tagsTitle: "Etiketler",
        allNotes: "T\xFCm Notlar",
        sortRecent: "\u{1F4C5} En Yeni",
        sortOldest: "\u{1F550} En Eski",
        sortAlphabetical: "\u{1F524} A-Z",
        pinned: "Sabitlendi",
        today: "Bug\xFCn",
        yesterday: "D\xFCn",
        thisWeek: "Bu Hafta",
        thisMonth: "Bu Ay",
        older: "Daha Eski"
      },
      chat: {
        title: "Yapay Zeka Sohbet Asistan\u0131",
        open: "Sohbeti A\xE7",
        close: "Sohbeti Kapat",
        placeholder: "Herhangi bir \u015Fey sorun...",
        send: "G\xF6nder",
        thinking: "D\xFC\u015F\xFCn\xFCyor...",
        startConversation: "Ba\u015Flamak i\xE7in bana bir soru sorun!",
        sessionError: "Sohbet oturumu ba\u015Flat\u0131lamad\u0131. L\xFCtfen tekrar deneyin.",
        toggleWebSearch: "Web Aramas\u0131n\u0131 A\xE7/Kapat",
        sources: "Kaynaklar",
        insertToEditor: "Edit\xF6re Ekle",
        insertedToEditor: "Edit\xF6re eklendi"
      },
      contextMenu: {
        improve: "Yaz\u0131y\u0131 iyile\u015Ftir",
        fix: "Yaz\u0131m ve dilbilgisini d\xFCzelt",
        summarize: "\xD6zetle",
        generateTags: "Etiket Olu\u015Ftur",
        describeImage: "Resmi betimle",
        suggestCaption: "Bir ba\u015Fl\u0131k \xF6ner",
        makeTable: "Tabloya d\xF6n\xFC\u015Ft\xFCr",
        shareSelection: "Se\xE7imi payla\u015F",
        shareImage: "Resmi payla\u015F",
        setReminder: "Hat\u0131rlat\u0131c\u0131 Ayarla",
        defaultSelectionTitle: "Neural Pad Se\xE7imi",
        table: {
          title: "Tablo",
          sortAZ: "A\u2192Z s\u0131rala (s\xFCtun)",
          sortZA: "Z\u2192A s\u0131rala (s\xFCtun)",
          totals: "Toplam sat\u0131r\u0131 ekle",
          zebra: "Zebra \u015Ferit",
          sticky: "Sabit ba\u015Fl\u0131k",
          borders: "Kenarl\u0131klar",
          bordersAll: "T\xFCm\xFC",
          bordersOutside: "D\u0131\u015F",
          bordersNone: "Yok",
          copyCsv: "CSV olarak kopyala"
        },
        customPromptPlaceholder: "Veya kendi isteminizi yaz\u0131n...",
        submit: "G\xF6nder"
      },
      settings: {
        title: "Ayarlar",
        theme: "G\xF6r\xFCn\xFCm",
        themes: {
          default: "Varsay\u0131lan",
          twilight: "Alacakaranl\u0131k",
          ocean: "Okyanus",
          forest: "Orman",
          blossom: "\xC7i\xE7ek",
          dusk: "\u015Eafak"
        },
        language: "Dil",
        autoSave: "Otomatik Kaydet",
        autoSaveDescription: "Mevcut notu her 5 dakikada bir otomatik olarak kaydeder.",
        apiProvider: "Yapay Zeka Sa\u011Flay\u0131c\u0131s\u0131",
        modelConfig: "Gemini Model Yap\u0131land\u0131rmas\u0131",
        model: "Model",
        temperature: "S\u0131cakl\u0131k",
        topK: "Top-K",
        topP: "Top-P",
        apiKey: "API Anahtar\u0131",
        apiKeyPlaceholder: "API anahtar\u0131n\u0131z\u0131 buraya girin",
        getApiKeyHere: "{{provider}} API anahtar\u0131n\u0131z\u0131 buradan al\u0131n",
        deleteApiKey: "API Anahtar\u0131n\u0131 Sil",
        confirmDeleteApiKey: "Bu API anahtar\u0131n\u0131 silmek istedi\u011Finizden emin misiniz? Bu i\u015Flem geri al\u0131namaz.",
        apiKeyDeleted: "API anahtar\u0131 ba\u015Far\u0131yla silindi",
        showApiKey: "API Anahtar\u0131n\u0131 G\xF6ster",
        hideApiKey: "API Anahtar\u0131n\u0131 Gizle",
        export: {
          title: "D\u0131\u015Fa Aktar & Yedekle",
          backupTitle: "Tam Yedekleme",
          backupDescription: "T\xFCm notlar\u0131 ve ayarlar\u0131 JSON olarak indirin. Cihaz\u0131n\u0131z\u0131 formatlamadan \xF6nce yedekleme i\xE7in m\xFCkemmel.",
          downloadBackup: "Tam Yede\u011Fi \u0130ndir",
          restoreBackup: "Yede\u011Fi Geri Y\xFCkle",
          importSuccess: "{{count}} not ba\u015Far\u0131yla i\xE7e aktar\u0131ld\u0131!",
          importError: "Yedek i\xE7e aktar\u0131lamad\u0131",
          exportTitle: "Belge Olarak D\u0131\u015Fa Aktar",
          exportDescription: "T\xFCm notlar\u0131 ZIP ar\u015Fivinde HTML veya Markdown dosyalar\u0131 olarak d\u0131\u015Fa aktar\u0131n."
        }
      },
      notifications: {
        noteSaved: "Not ba\u015Far\u0131yla kaydedildi!",
        saveError: "Not kaydedilemedi: {{message}}",
        noteDeleted: "Not silindi.",
        deleteError: "Not silinemedi: {{message}}",
        loadError: "Notlar y\xFCklenemedi: {{message}}",
        aiThinking: "Yapay zeka d\xFC\u015F\xFCn\xFCyor...",
        aiSuccess: "Yapay zeka g\xF6revi tamamland\u0131!",
        aiError: "Yapay Zeka Hatas\u0131: {{message}}",
        quotaError: "{{provider}} i\xE7in kotan\u0131z\u0131 a\u015Ft\u0131n\u0131z. L\xFCtfen plan\u0131n\u0131z\u0131 ve fatura detaylar\u0131n\u0131z\u0131 web sitelerinden kontrol edin.",
        apiKeyInvalid: "{{provider}} API anahtar\u0131n\u0131z ge\xE7ersiz veya eksik g\xF6r\xFCn\xFCyor. L\xFCtfen Ayarlar'dan kontrol edin.",
        apiKeyMissingAction: "API anahtar\u0131 eksik. Ayarlar'\u0131 a\xE7mak i\xE7in buraya t\u0131klay\u0131n.",
        noTagsFound: "\u0130lgili etiket bulunamad\u0131.",
        noteLocked: "Not kilitlendi.",
        wrongPassword: "\u015Eifre yanl\u0131\u015F.",
        lockRemoved: "Kilit kald\u0131r\u0131ld\u0131.",
        cannotSaveLocked: "\u015Eifre olmadan kilitli not kaydedilemez.",
        shareSuccess: "Ba\u015Far\u0131yla payla\u015F\u0131ld\u0131.",
        shareUnavailable: "Payla\u015F\u0131m burada desteklenmiyor. Panoya kopyaland\u0131.",
        exportedAsJson: "Not ba\u015Far\u0131yla JSON olarak d\u0131\u015Fa aktar\u0131ld\u0131!",
        exportSuccess: "{{format}} olarak ba\u015Far\u0131yla d\u0131\u015Fa aktar\u0131ld\u0131!",
        exportError: "D\u0131\u015Fa aktarma ba\u015Far\u0131s\u0131z: {{message}}"
      },
      common: {
        save: "Kaydet",
        cancel: "\u0130ptal",
        delete: "Sil",
        close: "Kapat",
        apply: "Uygula",
        preview: "\xD6nizleme",
        markdown: "Markdown",
        loading: "Y\xFCkleniyor...",
        restore: "Geri Y\xFCkle"
      },
      saveAs: {
        title: "Farkl\u0131 Kaydet",
        filename: "Dosya Ad\u0131",
        format: "Kay\u0131t T\xFCr\xFC",
        selectFormat: "Notunuzu d\u0131\u015Fa aktarmak i\xE7in bir format se\xE7in",
        export: "D\u0131\u015Fa Aktar"
      },
      history: {
        title: "Ge\xE7mi\u015F",
        empty: "Hen\xFCz ge\xE7mi\u015F kayd\u0131 yok",
        selectVersion: "Bir versiyon se\xE7in"
      },
      welcome: {
        title: "Neural Pad'e Ho\u015F Geldiniz",
        subtitle: "Google Gemini taraf\u0131ndan desteklenen ak\u0131ll\u0131 yaz\u0131 arkada\u015F\u0131n\u0131z. Yarat\u0131c\u0131l\u0131\u011F\u0131n\u0131z\u0131 art\u0131r\u0131n, i\u015F ak\u0131\u015F\u0131n\u0131z\u0131 kolayla\u015Ft\u0131r\u0131n ve fikirlerinizi hayata ge\xE7irin.",
        feature1Title: "Yapay Zeka Destekli Yaz\u0131",
        feature1Description: "Se\xE7ti\u011Finiz metni tek bir t\u0131klamayla iyile\u015Ftirin, \xF6zetleyin veya dilbilgisini d\xFCzeltin.",
        feature2Title: "G\xF6rsel Zeka",
        feature2Description: "A\xE7\u0131klamalar veya yarat\u0131c\u0131 ba\u015Fl\u0131klar olu\u015Fturmak i\xE7in resimlere sa\u011F t\u0131klay\u0131n.",
        feature3Title: "Sohbet Tabanl\u0131 Yapay Zeka",
        feature3Description: "Fikir al\u0131\u015Fveri\u015Fi yapmak, soru sormak veya ara\u015Ft\u0131rma yard\u0131m\u0131 almak i\xE7in yapay zeka ile sohbet edin.",
        feature4Title: "Ak\u0131ll\u0131 Organizasyon",
        feature4Description: "Her \u015Feyi d\xFCzenli tutmak i\xE7in notlar\u0131n\u0131z i\xE7in otomatik olarak ilgili etiketler olu\u015Fturun.",
        cta: "Ba\u015Flay\u0131n",
        quickLinks: {
          features: "\xD6zellikler",
          items: {
            aiChat: "AI Sohbet",
            imageAnalysis: "G\xF6rsel Analiz",
            tagging: "Etiketleme"
          },
          support: "Destek",
          privacyPolicy: "Gizlilik Politikas\u0131",
          termsOfService: "Hizmet \u015Eartlar\u0131",
          contact: "\u0130leti\u015Fim"
        }
      },
      landingPage: {
        heroTitle: "Ak\u0131ll\u0131 Not Tutman\u0131n Gelece\u011Fi",
        heroSubtitle: "AI destekli ak\u0131ll\u0131 not defteri. Notlar\u0131n\u0131z\u0131 yaz\u0131n, organize edin, g\xFCvenle saklay\u0131n ve yapay zeka ile geli\u015Ftirin.",
        cta: "Yazar'\u0131 Ba\u015Flat",
        featuresTitle: "Netlik ve G\xFC\xE7 \u0130\xE7in Tasarland\u0131",
        mockupsTitle: "Uygulamadan G\xF6rseller",
        mockupsSubtitle: "\xD6ne \xE7\u0131kan ekran g\xF6r\xFCnt\xFCleri",
        mockupsItems: {
          i1: { title: "Yaz\u0131y\u0131 \u0130yile\u015Ftir", desc: "Se\xE7ili metni YZ ile daha net, ak\u0131c\u0131 ve etkileyici hale getir." },
          i2: { title: "Dilbilgisi ve Yaz\u0131m", desc: "Hatalar\u0131 otomatik d\xFCzelt, tonu koru." },
          i3: { title: "\xD6zetle", desc: "Uzun metni birka\xE7 ana maddeye indir." },
          i4: { title: "Etiket Olu\u015Ftur", desc: "Not i\xE7in alakal\u0131 etiketleri otomatik \xFCret." },
          i5: { title: "Blueprint Olu\u015Ftur", desc: "Se\xE7imden Make.com blueprint \xFCret." },
          i6: { title: "Ba\u015Fl\u0131k \xD6ner", desc: "G\xF6rseller i\xE7in yarat\u0131c\u0131 ba\u015Fl\u0131klar \xF6ner." },
          i7: { title: "G\xF6rseli A\xE7\u0131kla", desc: "Resmi yapay zeka ayr\u0131nt\u0131l\u0131 bi\xE7imde betimler." },
          i8: { title: "Sohbet Asistan\u0131", desc: "Ba\u011Flama duyarl\u0131 sohbetle fikir \xFCret ve ara\u015Ft\u0131r." }
        },
        newFeaturesTitle: "Yeni \xD6zellikler",
        newFeatures: {
          backupTitle: "D\u0131\u015Fa Aktar & Yedekle",
          backupDesc: "T\xFCm notlar\u0131 HTML/Markdown veya tam JSON yede\u011Fi olarak indirin.",
          secureTitle: "\u015Eifreli Notlar",
          secureDesc: "Notlar\u0131 \u015Fifreyle kilitleyin. \u0130\xE7erik \u015Fifreli kal\u0131r."
        },
        downloadTitle: "Masa\xFCst\xFC Uygulamas\u0131n\u0131 Edinin",
        downloadSubtitle: "Favori i\u015Fletim sisteminizde odaklanm\u0131\u015F, yerel bir deneyimin keyfini \xE7\u0131kar\u0131n. (Yak\u0131nda)",
        downloadFor: "\u0130\xE7in \u0130ndir",
        footerText: "\xA9 {{year}} Neural Pad. T\xFCm haklar\u0131 sakl\u0131d\u0131r.",
        contactEmail: "\u0130leti\u015Fim:"
      },
      help: {
        title: "Yard\u0131m & K\u0131sayollar",
        quickStart: "H\u0131zl\u0131 Ba\u015Flang\u0131\xE7",
        quickStartStep1: "Kenar \xE7ubu\u011Fundan yeni bir not olu\u015Fturun ve ba\u015Fl\u0131k verin.",
        quickStartStep2: "Yazmaya ba\u015Flay\u0131n. Metni se\xE7ip sa\u011F t\u0131klayarak YZ eylemlerini kullan\u0131n.",
        quickStartStep3: "Beyin f\u0131rt\u0131nas\u0131 veya ara\u015Ft\u0131rma i\xE7in Sohbet'i a\xE7\u0131n.",
        quickStartStep4: "Ayarlar'dan YZ sa\u011Flay\u0131c\u0131s\u0131, tema ve d\u0131\u015Fa aktarma se\xE7eneklerini kullan\u0131n.",
        writingAssistant: "YZ Yaz\u0131 Asistan\u0131",
        writingAssistantDesc: "D\xFCzenleyicide herhangi bir metni se\xE7in ve YZ ba\u011Flam men\xFCs\xFCn\xFC a\xE7mak i\xE7in sa\u011F t\u0131klay\u0131n. Yaz\u0131y\u0131 iyile\u015Ftirebilir, dilbilgisini d\xFCzeltebilir, \xF6zetleyebilir ve daha fazlas\u0131n\u0131 yapabilirsiniz.",
        imageTools: "YZ G\xF6r\xFCnt\xFC Ara\xE7lar\u0131",
        imageToolsDesc: "A\xE7\u0131klamalar veya ba\u015Fl\u0131klar olu\u015Fturmak i\xE7in d\xFCzenleyiciye yap\u0131\u015Ft\u0131rd\u0131\u011F\u0131n\u0131z herhangi bir resme sa\u011F t\u0131klay\u0131n. Mobilde, resim \xFCzerindeki sihirli de\u011Fnek simgesine dokunun.",
        chat: "YZ Sohbet",
        chatDesc: "YZ ile sohbet etmek i\xE7in sohbet kenar \xE7ubu\u011Funu a\xE7\u0131n. Beyin f\u0131rt\u0131nas\u0131, ara\u015Ft\u0131rma veya sorular\u0131 yan\u0131tlama konusunda yard\u0131mc\u0131 olabilir. G\xFCncel bilgiler i\xE7in web aramas\u0131n\u0131 a\xE7\u0131n.",
        organization: "Organizasyon & Etiketler",
        organizationDesc: "Notlar\u0131n\u0131z\u0131 otomatik olarak etiketlemek i\xE7in 'Etiket Olu\u015Ftur' YZ eylemini kullan\u0131n. Kenar \xE7ubu\u011Funda notlar\u0131n\u0131z\u0131 etikete g\xF6re filtreleyin.",
        voiceInput: "Sesli Giri\u015F",
        voiceInputDesc: "Ellerinizi kullanmadan sesli olarak not yaz\u0131n.",
        voiceInputStep1: "Ara\xE7 \xE7ubu\u011Fundaki mikrofon ikonuna t\u0131klay\u0131n",
        voiceInputStep2: "Net ve yava\u015F konu\u015Fun",
        voiceInputStep3: "Modaldaki yaz\u0131ya d\xF6n\xFC\u015Ft\xFCr\xFClm\xFC\u015F metni kontrol edin",
        voiceInputStep4: "Nota eklemek i\xE7in 'Ekle', iptal i\xE7in '\u0130ptal' butonuna bas\u0131n",
        exportBackup: "D\u0131\u015Fa Aktar & Yedekle",
        backupTitle: "Yedekleme Nas\u0131l Yap\u0131l\u0131r",
        backupStep1: "Ayarlar'\u0131 a\xE7\u0131n (\xFCst \xE7ubukta di\u015Fli ikonu)",
        backupStep2: "'D\u0131\u015Fa Aktar & Yedekle' b\xF6l\xFCm\xFCne gidin",
        backupStep3: "'\u{1F4E6} Tam Yede\u011Fi \u0130ndir' butonuna t\u0131klay\u0131n - JSON dosyas\u0131 olarak kaydedilir",
        restoreTitle: "Geri Y\xFCkleme Nas\u0131l Yap\u0131l\u0131r",
        restoreStep1: "Format att\u0131ktan sonra uygulama a\xE7\u0131n",
        restoreStep2: "Ayarlar \u2192 D\u0131\u015Fa Aktar & Yedekle b\xF6l\xFCm\xFCne gidin",
        restoreStep3: "'\u{1F4E5} Yede\u011Fi Geri Y\xFCkle' butonuna t\u0131klay\u0131n",
        restoreStep4: "JSON yedek dosyan\u0131z\u0131 se\xE7in - t\xFCm veriler geri gelecek!",
        backupTip: "\u0130pucu:",
        backupTipDesc: "Yedek dosyan\u0131z\u0131 ekstra g\xFCvenlik i\xE7in bulut depolama alan\u0131nda (Google Drive, Dropbox) saklay\u0131n.",
        exportBackupDesc: "Ayarlar \u2192 Export b\xF6l\xFCm\xFCnden t\xFCm notlar\u0131 HTML veya Markdown (ZIP) olarak indirebilirsiniz.",
        storageSecurity: "Depolama & G\xFCvenlik",
        storageSecurityDesc: "Notlar\u0131n\u0131z taray\u0131c\u0131n\u0131zda yerel olarak (IndexedDB) saklan\u0131r. Kilitli notlar \u015Fifrenizle \u015Fifrelenir\u2014\u015Fifre olmadan i\xE7erik kurtar\u0131lamaz.",
        shortcuts: "Klavye K\u0131sayollar\u0131",
        saveNote: "Mevcut notu kaydet",
        bold: "Kal\u0131n",
        italic: "\u0130talik",
        underline: "Alt\u0131n\u0131 \xE7iz",
        undo: "Geri Al",
        redo: "Yinele",
        troubleshooting: "Sorun Giderme",
        troubleshootingWindow: "Electron penceresi g\xF6r\xFCnm\xFCyor: dev sunucu ba\u015Flad\u0131ktan sonra birka\xE7 saniye bekleyin; gerekirse Ctrl+Shift+I ile Geli\u015Ftirici Ara\xE7lar\u0131'n\u0131 a\xE7\u0131p hatalar\u0131 kontrol edin.",
        troubleshootingApi: "API anahtar\u0131 uyar\u0131s\u0131: Ayarlar'\u0131 a\xE7\u0131p sa\u011Flay\u0131c\u0131 anahtar\u0131n\u0131z\u0131 ekleyin.",
        troubleshootingImages: "Resim yap\u0131\u015Fm\u0131yor: panoda resim oldu\u011Fundan emin olun; s\xFCr\xFCkle-b\u0131rak yap\u0131n veya ara\xE7 \xE7ubu\u011Fundan y\xFCkleyin."
      },
      aiPrompts: {
        languageInstruction: "L\xFCtfen yan\u0131t\u0131 se\xE7ilen metinle ayn\u0131 dilde sa\u011Flay\u0131n.",
        responseTitle: "Yapay Zeka Yan\u0131t\u0131",
        improveWriting: "A\u015Fa\u011F\u0131daki metnin yaz\u0131m\u0131n\u0131 daha net, \xF6z ve ilgi \xE7ekici hale getirerek iyile\u015Ftirin",
        fixSpelling: "A\u015Fa\u011F\u0131daki metindeki yaz\u0131m ve dilbilgisi hatalar\u0131n\u0131 d\xFCzeltin",
        summarize: "A\u015Fa\u011F\u0131daki metni birka\xE7 ana noktaya \xF6zetleyin",
        generateTags: "A\u015Fa\u011F\u0131daki metin i\xE7in ilgili etiketler olu\u015Fturun",
        describeImage: "Bu resmi ayr\u0131nt\u0131l\u0131 olarak a\xE7\u0131klay\u0131n",
        suggestCaption: "Bu resim i\xE7in yarat\u0131c\u0131 ve ilgi \xE7ekici bir ba\u015Fl\u0131k \xF6nerin",
        makeTable: "Se\xE7ilen metni net bir tabloya d\xF6n\xFC\u015Ft\xFCr. Yorum olmadan yaln\u0131zca CSV \xE7\u0131kt\u0131 ver."
      },
      openNote: {
        noNotes: "Hen\xFCz not yok. Bir tane olu\u015Fturun!"
      },
      password: {
        setTitle: "\u015Eifre Belirle",
        unlockTitle: "\u015Eifre Girin",
        removeTitle: "Kilidi Kald\u0131r",
        passwordLabel: "\u015Eifre",
        placeholder: "\u015Eifrenizi girin",
        confirm: "Onayla"
      },
      voice: {
        start: "Sesli Giri\u015Fi Ba\u015Flat",
        stop: "Sesli Giri\u015Fi Durdur",
        error: "Ses tan\u0131ma hatas\u0131",
        networkError: "A\u011F hatas\u0131. L\xFCtfen internet ba\u011Flant\u0131n\u0131z\u0131 kontrol edin.",
        permissionError: "Mikrofon izni reddedildi. L\xFCtfen taray\u0131c\u0131 ayarlar\u0131n\u0131 kontrol edin.",
        serviceNotAllowedError: "Ses tan\u0131ma servisi kullan\u0131lam\u0131yor. L\xFCtfen taray\u0131c\u0131 ayarlar\u0131n\u0131 kontrol edin.",
        badGrammarError: "Ses tan\u0131ma dilbilgisi hatas\u0131. L\xFCtfen tekrar deneyin.",
        languageNotSupportedError: "Desteklenmeyen dil. L\xFCtfen farkl\u0131 bir dil se\xE7in.",
        listening: "Dinleniyor...",
        processing: "\u0130\u015Fleniyor...",
        readyToRecord: "Kay\u0131t i\xE7in haz\u0131r",
        insert: "Ekle"
      },
      toolbar: {
        bold: "Kal\u0131n",
        italic: "\u0130talik",
        underline: "Alt \xC7izgi",
        strike: "\xDCst\xFC \xC7izgili",
        code: "Kod",
        bulletList: "Madde \u0130\u015Faretli Liste",
        orderedList: "Numaral\u0131 Liste",
        blockquote: "Al\u0131nt\u0131",
        insertImage: "Resim Ekle",
        attachFile: "Dosya Ekle",
        insertTable: "Tablo Ekle",
        undo: "Geri Al",
        redo: "Yinele"
      },
      share: {
        title: "Notu Payla\u015F",
        email: "E-posta",
        copy: "Kopyala",
        download: "\u0130ndir",
        format: "Format Se\xE7",
        htmlNote: "Resimler dahil, taray\u0131c\u0131da a\xE7\u0131labilir",
        pdfNote: "Yazd\u0131rma penceresi a\xE7\u0131lacak",
        jsonNote: "Yedekleme/programlama i\xE7in",
        txtNote: "Sadece metin",
        pdfPrintOpened: "PDF yazd\u0131rma penceresi a\xE7\u0131ld\u0131",
        systemShare: "Sistem Payla\u015F\u0131m\u0131 (Dosya)",
        systemShareDesc: "Dosya olarak payla\u015F (Mail, Outlook vb.)",
        or: "VEYA",
        fullNote: "T\xFCm Not",
        selection: "Se\xE7ili Alan",
        shareAsText: "Metin Olarak Payla\u015F",
        otherActions: "Di\u011Fer \u0130\u015Flemler"
      },
      reminder: {
        title: "\u{1F514} Hat\u0131rlat\u0131c\u0131 Ayarla",
        quickOptions: "H\u0131zl\u0131 Se\xE7enekler",
        in1Hour: "1 saat sonra",
        in3Hours: "3 saat sonra",
        tomorrow: "Yar\u0131n sabah",
        nextWeek: "1 hafta sonra",
        customDate: "\xD6zel Tarih/Saat",
        addToCalendar: "Takvime Ekle",
        save: "Kaydet",
        remove: "Kald\u0131r",
        setSuccess: "Hat\u0131rlat\u0131c\u0131 ayarland\u0131!",
        removed: "Hat\u0131rlat\u0131c\u0131 kald\u0131r\u0131ld\u0131",
        pastDateError: "Ge\xE7mi\u015F bir tarih se\xE7emezsiniz",
        selectDateFirst: "\xD6nce bir tarih se\xE7in",
        calendarOpened: "Takvim a\xE7\u0131ld\u0131",
        reminderNotification: "\u23F0 Hat\u0131rlat\u0131c\u0131: {{title}}",
        alertTitle: "\u23F0 Hat\u0131rlat\u0131c\u0131!",
        goToNote: "Nota Git"
      }
    }
  };
})();
